---
name: DigitalOcean K*s
description: >
  Add flex volume support for digitalocean
version: 0.0.1-rancher1
category: DigitalOcean
maintainer: Evan Hegyi <evan@evanhegyi.com>
license: MIT
projectURL: https://github.com/evan111/RancherTemplate
