---
name: DigitalOcean K*s
description: >
  Add flex volume support for digitalocean
version: v1.3.0-rancher4
category: DigitalOcean
maintainer: Evan Hegyi <evan@evanhegyi.com>
license: MIT
projectURL: https://github.com/evan111/RancherTemplate
